---
- hosts: all
  connection: local

  vars_files:
      - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
     - ansible-role-dotfiles
    - ansible-role-homebrew
    - ansible-role-sublimetext
    - ansible-role-mas


  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/directory-setup.yml
    - include: tasks/python-setup.yml
    - include: tasks/git-prompt-setup.yml
    - include: tasks/vim-setup.yml
    - include: tasks/fonts-setup.yml
    - include: tasks/preferences.yml
